version: '3.3'

networks:
  main:

services:

  minitwitimage:
    image: ${DOCKER_USERNAME}/minitwitimage
    container_name: minitwit
    networks:
      - main
    depends_on:
      - itusqlimage
    ports:
        - '5000:5000'

  itusqlimage:
    image: ${DOCKER_USERNAME}/itusqlimage
    container_name: minitwit_mysql
    networks:
      - main
    ports:
      - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=root
